
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AplikasiKonversiSuhuFrame extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhuFrame
     */
    public AplikasiKonversiSuhuFrame() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(radioCelsiusToFahrenheit);
        group.add(radioFahrenheitToCelsius);
        group.add(radioCelsiusToReamur);
        group.add(radioFahrenheitToReamur);
        
        comboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Reamur", "Kelvin" }));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        labelInput = new javax.swing.JLabel();
        textFieldInput = new javax.swing.JTextField();
        comboBoxScale = new javax.swing.JComboBox<>();
        radioCelsiusToFahrenheit = new javax.swing.JRadioButton();
        radioFahrenheitToCelsius = new javax.swing.JRadioButton();
        buttonConvert = new javax.swing.JButton();
        labelResult = new javax.swing.JLabel();
        textFieldResult = new javax.swing.JTextField();
        radioCelsiusToReamur = new javax.swing.JRadioButton();
        radioFahrenheitToReamur = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 162, 94));

        labelTitle.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelTitle.setText("Aplikasi Konversi Suhu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(labelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(160, 71, 71));

        labelInput.setText("Masukan Suhu");

        textFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldInputActionPerformed(evt);
            }
        });
        textFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldInputKeyTyped(evt);
            }
        });

        comboBoxScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        radioCelsiusToFahrenheit.setText("Celsius to Fahrenheit");
        radioCelsiusToFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCelsiusToFahrenheitActionPerformed(evt);
            }
        });

        radioFahrenheitToCelsius.setText("Fahrenheit to Celsius");

        buttonConvert.setBackground(new java.awt.Color(238, 223, 122));
        buttonConvert.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        buttonConvert.setText("Konversi");
        buttonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConvertActionPerformed(evt);
            }
        });

        labelResult.setText("Hasil");

        textFieldResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldResultActionPerformed(evt);
            }
        });

        radioCelsiusToReamur.setText("Celsius ke Reamur");

        radioFahrenheitToReamur.setText("Fahrenheit ke Reamur");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxScale, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(labelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldInput))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radioCelsiusToFahrenheit, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(radioFahrenheitToCelsius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radioCelsiusToReamur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioFahrenheitToReamur, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                            .addComponent(textFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInput)
                    .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCelsiusToFahrenheit)
                    .addComponent(radioCelsiusToReamur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFahrenheitToCelsius)
                    .addComponent(radioFahrenheitToReamur))
                .addGap(21, 21, 21)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResult)
                    .addComponent(textFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(buttonConvert)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldInputActionPerformed

    private void textFieldResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldResultActionPerformed

    private void radioCelsiusToFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCelsiusToFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCelsiusToFahrenheitActionPerformed

    private void buttonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConvertActionPerformed
        try {
        // Mengambil nilai suhu yang dimasukkan oleh pengguna
        String inputText = textFieldInput.getText();

        // Pengecekan jika input kosong
        if (inputText.isEmpty()) {
            textFieldResult.setText("Masukkan suhu yang valid!");
            return; // Menghentikan proses konversi jika input kosong
        }

        // Mengonversi input menjadi angka
        double inputSuhu = Double.parseDouble(inputText);

        // Pengecekan jika suhu terlalu rendah (di bawah -273.15°C atau 0 Kelvin)
        if (inputSuhu < -273.15) {  // Suhu lebih rendah dari -273.15°C
            textFieldResult.setText("Suhu terlalu rendah!");
            return; // Menghentikan proses jika suhu terlalu rendah
        }

        // Lakukan konversi berdasarkan input yang valid
        String selectedScale = (String) comboBoxScale.getSelectedItem();  // Pilihan skala suhu
        double hasilKonversi = 0.0;

        // Mengecek arah konversi yang dipilih dan melakukan konversi berdasarkan skala suhu yang dipilih
        if ("Celsius".equals(selectedScale)) {
            if (radioCelsiusToFahrenheit.isSelected()) {
                hasilKonversi = (inputSuhu * 9 / 5) + 32; // Rumus Celsius ke Fahrenheit
            } else if (radioCelsiusToReamur.isSelected()) {
                hasilKonversi = inputSuhu * 4 / 5; // Rumus Celsius ke Reamur
            }
        } else if ("Fahrenheit".equals(selectedScale)) {
            if (radioFahrenheitToCelsius.isSelected()) {
                hasilKonversi = (inputSuhu - 32) * 5 / 9; // Rumus Fahrenheit ke Celsius
            } else if (radioFahrenheitToReamur.isSelected()) {
                hasilKonversi = (inputSuhu - 32) * 4 / 9; // Rumus Fahrenheit ke Reamur
            }
        }

        // Menampilkan hasil konversi di textFieldResult
        textFieldResult.setText(String.valueOf(hasilKonversi));

    } catch (NumberFormatException e) {
        textFieldResult.setText("Masukkan suhu yang valid!"); // Jika input bukan angka
    }

    }//GEN-LAST:event_buttonConvertActionPerformed

    private void textFieldInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldInputKeyTyped
        char karakter = evt.getKeyChar();
    // Memeriksa apakah karakter bukan digit dan bukan karakter kontrol (backspace, delete, dll.)
    if (!Character.isDigit(karakter) && karakter != KeyEvent.VK_BACK_SPACE && karakter != KeyEvent.VK_DELETE) {
        evt.consume();
        JOptionPane.showMessageDialog(this, "Masukkan hanya angka!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_textFieldInputKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConvert;
    private javax.swing.JComboBox<String> comboBoxScale;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInput;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton radioCelsiusToFahrenheit;
    private javax.swing.JRadioButton radioCelsiusToReamur;
    private javax.swing.JRadioButton radioFahrenheitToCelsius;
    private javax.swing.JRadioButton radioFahrenheitToReamur;
    private javax.swing.JTextField textFieldInput;
    private javax.swing.JTextField textFieldResult;
    // End of variables declaration//GEN-END:variables
}
